spring:
  cloud:
    stream:
      dynamic-destinations:
        - test
        - test2
      bindings:
        input:
          destination: test,test1
          binder: kafka1
          content-type: text/plain
          consumer:
            header-mode: raw 
        output:
          destination: test2
          binder: kafka1
          content-type: text/plain
      binders:
        kafka1:
          type: kafka
          environment:
            spring:
              kafka:
                host: localhost:9092 