spring:
  cloud:
    stream:
      dynamic-destinations:
        - test
      bindings:
        inputChannel1:
          destination: test
          binder: kafka1
          content-type: binary/avro
          consumer:
            header-mode: raw 
        outputChannel1:
          destination: test
          binder: kafka1
          producer:
            headerMode: raw
        outputChannel2:
          destination: test1
          binder: kafka1
      binders:
        kafka1:
          type: kafka
          environment:
            spring:
              kafka:
                host: localhost:9092 